/* eslint-disable no-restricted-globals */

// This file is the service worker.

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache all files generated by your build process.
precacheAndRoute(self.__WB_MANIFEST || []);

// Example of a runtime caching route for images
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
  })
);

// Function to check for a valid service worker
const checkValidServiceWorker = (swUrl) => {
  fetch(swUrl)
    .then((response) => {
      if (
        response.status === 404 ||
        response.headers.get('content-type')?.indexOf('javascript') === -1
      ) {
        //
        // No valid service worker found; unregister it.
        navigator.serviceWorker.ready.then((registration) => {
          registration.unregister().then(() => {
            console.log('Service worker unregistered. Reloading...');
            window.location.reload();
          });
        });
      } else {
        console.log('Valid service worker found.');
      }
    })
    .catch(() => {
      console.error('No internet connection found. App is running in offline mode.');
    });
};

// Example usage of the checkValidServiceWorker function
const swUrl = `${process.env.PUBLIC_URL}/service-worker.js`;
checkValidServiceWorker(swUrl);
